# Cargo configuration for Android cross-compilation
# This file should be placed in the project root as .cargo/config.toml

[target.aarch64-linux-android]
ar = "aarch64-linux-android-ar"
linker = "aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "arm-linux-androideabi-ar"
linker = "armv7a-linux-androideabi21-clang"

[target.x86_64-linux-android]
ar = "x86_64-linux-android-ar"
linker = "x86_64-linux-android21-clang"

[target.i686-linux-android]
ar = "i686-linux-android-ar"
linker = "i686-linux-android21-clang"

[env]
# Set Android NDK path - adjust this to your actual NDK installation
ANDROID_NDK_HOME = { value = "C:\\Users\\%USERNAME%\\AppData\\Local\\Android\\Sdk\\ndk\\26.1.10909125", force = true }
# Alternative common paths:
# ANDROID_NDK_HOME = { value = "C:\\Android\\android-ndk-r26c", force = true }
# ANDROID_NDK_HOME = { value = "%LOCALAPPDATA%\\Android\\Sdk\\ndk-bundle", force = true }

# Add NDK toolchain to PATH
PATH = { value = "%ANDROID_NDK_HOME%\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin;%PATH%", force = true }
